import { InventoryTypes } from "~/schema/inventory";
export const medicalInventorySamples = [
  // MEDICINES
  {
    name: "Paracetamol",
    description: "Pain reliever and fever reducer",
    price: 5000,
    stock: 1000,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Amoxicillin",
    description: "Broad-spectrum antibiotic",
    price: 25000,
    stock: 500,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Omeprazole",
    description: "Acid reflux medication",
    price: 35000,
    stock: 300,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Insulin",
    description: "Diabetes medication",
    price: 150000,
    stock: 200,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Metformin",
    description: "Type 2 diabetes medication",
    price: 45000,
    stock: 400,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Amlodipine",
    description: "Blood pressure medication",
    price: 30000,
    stock: 350,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Simvastatin",
    description: "Cholesterol-lowering medication",
    price: 40000,
    stock: 300,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Sertraline",
    description: "Antidepressant medication",
    price: 65000,
    stock: 200,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Albuterol Inhaler",
    description: "Asthma medication",
    price: 85000,
    stock: 150,
    type: InventoryTypes.MEDICINE,
  },
  {
    name: "Cetirizine",
    description: "Antihistamine for allergies",
    price: 15000,
    stock: 600,
    type: InventoryTypes.MEDICINE,
  },
  // AIDS (ALAT BANTU)
  {
    name: "Tongkat Jalan",
    description: "Alat bantu jalan standar dengan grip anti-slip",
    price: 250000,
    stock: 50,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Walker Adjustable",
    description:
      "Alat bantu jalan dengan 4 kaki yang dapat disesuaikan tingginya",
    price: 750000,
    stock: 30,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Kruk Aluminium",
    description: "Kruk ringan dengan penyangga lengan yang nyaman",
    price: 450000,
    stock: 40,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Alat Bantu Dengar Digital",
    description: "Alat bantu dengar dengan teknologi noise reduction",
    price: 3500000,
    stock: 15,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Kacamata Baca Adjustable",
    description: "Kacamata baca dengan diopter yang dapat disesuaikan",
    price: 850000,
    stock: 25,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Kursi Toilet Portable",
    description: "Kursi toilet yang dapat dipindahkan dengan mudah",
    price: 1200000,
    stock: 20,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Matras Anti Dekubitus",
    description:
      "Matras khusus untuk mencegah luka tekan pada pasien tirah baring",
    price: 2500000,
    stock: 15,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Brace Lutut Adjustable",
    description: "Penyangga lutut dengan tingkat kompresi yang dapat diatur",
    price: 350000,
    stock: 45,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Cervical Collar",
    description: "Penyangga leher dengan foam density tinggi",
    price: 275000,
    stock: 35,
    type: InventoryTypes.AIDS,
  },
  {
    name: "Lumbar Support Belt",
    description: "Sabuk penyangga punggung bawah dengan double compression",
    price: 425000,
    stock: 40,
    type: InventoryTypes.AIDS,
  },
  // EQUIPMENT
  {
    name: "Blood Pressure Monitor",
    description: "Digital BP monitor",
    price: 750000,
    stock: 20,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Stethoscope",
    description: "Medical listening device",
    price: 500000,
    stock: 30,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Thermometer",
    description: "Digital thermometer",
    price: 100000,
    stock: 50,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Pulse Oximeter",
    description: "Oxygen saturation monitor",
    price: 300000,
    stock: 25,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "ECG Machine",
    description: "Electrocardiogram device",
    price: 15000000,
    stock: 5,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Defibrillator",
    description: "Emergency cardiac device",
    price: 25000000,
    stock: 3,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Ultrasound Machine",
    description: "Diagnostic imaging device",
    price: 50000000,
    stock: 2,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "X-Ray Machine",
    description: "Radiographic imaging system",
    price: 75000000,
    stock: 2,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Microscope",
    description: "Laboratory microscope",
    price: 3500000,
    stock: 10,
    type: InventoryTypes.EQUIPMENT,
  },
  {
    name: "Wheelchair",
    description: "Patient mobility device",
    price: 1500000,
    stock: 15,
    type: InventoryTypes.EQUIPMENT,
  },

  // SUPPLIES
  {
    name: "Surgical Gloves",
    description: "Disposable medical gloves",
    price: 2000,
    stock: 5000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Face Masks",
    description: "Medical-grade face masks",
    price: 1500,
    stock: 10000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Bandages",
    description: "Sterile wound dressing",
    price: 1000,
    stock: 2000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Syringes",
    description: "Disposable syringes",
    price: 500,
    stock: 3000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "IV Sets",
    description: "Intravenous administration sets",
    price: 15000,
    stock: 1000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Gauze Pads",
    description: "Sterile absorbent pads",
    price: 1000,
    stock: 5000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Alcohol Swabs",
    description: "Antiseptic wipes",
    price: 500,
    stock: 10000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Surgical Tape",
    description: "Medical adhesive tape",
    price: 3000,
    stock: 2000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Cotton Balls",
    description: "Sterile cotton balls",
    price: 500,
    stock: 8000,
    type: InventoryTypes.SUPPLY,
  },
  {
    name: "Tongue Depressors",
    description: "Wooden examination sticks",
    price: 300,
    stock: 5000,
    type: InventoryTypes.SUPPLY,
  },
];
